### ISSUE TITLE
"Get" and "Put" example

### ISSUE THREAD

**Issue by wowbl** [Tanganelli/CoAPthon#22]
Is there any way to pull out "Get" and "Put"  module ? 

I want to control Led through "PUT" and acquire fixed sources data through "GET".

**Comment by MarcoIeni** [comment]
Of course you can do this. I have no time to write an example (sorry about that), but I will explain how to do it. You can do GET, PUT and all the other REST requests with the coapclient:
https://github.com/Tanganelli/CoAPthon/blob/master/coapclient.py

while in the led or where you want to listen to any REST request you have to run the coapserver:
https://github.com/Tanganelli/CoAPthon/blob/master/coapserver.py and edit the resources in order to tell to the program what to do when a rest request ask for a specific resorce.

I hope that this was useful

**Comment by Venkat2811** [comment]
Hi @MarcoIeni / @Tanganelli ,

Is there any way to dynamically add resource to server using PUT when server is running ?

Thanks,
Venkat
